language: python
python:
  - "3.6"
  - "3.7"
  - "pypy3"

matrix:
  allow_failures:
    - python: "pypy3"

# command to install dependencies
install:
  - pip install flit
  - FLIT_ALLOW_INVALID=1 flit install

# command to run tests
script:
  - pytest --cov=lattices

after_success:
  - codecov

notifications:
  email: false
